name: MagnetPlugin
version: 1.0
main: com.erwin.magnetplugin.MagnetPlugin
api-version: 1.20
commands:
  magnet:
    description: Give yourself a magnet item that pulls nearby items
    usage: /magnet
